//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasoEstudioKN.BaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CasoEstudioKNEntities : DbContext
    {
        public CasoEstudioKNEntities()
            : base("name=CasoEstudioKNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasasSistema> CasasSistema { get; set; }
    
        public virtual int SP_AlquilarCasa(Nullable<long> idCasa, string usuarioAlquiler)
        {
            var idCasaParameter = idCasa.HasValue ?
                new ObjectParameter("IdCasa", idCasa) :
                new ObjectParameter("IdCasa", typeof(long));
    
            var usuarioAlquilerParameter = usuarioAlquiler != null ?
                new ObjectParameter("UsuarioAlquiler", usuarioAlquiler) :
                new ObjectParameter("UsuarioAlquiler", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AlquilarCasa", idCasaParameter, usuarioAlquilerParameter);
        }
    
        public virtual ObjectResult<SP_ListarCasas_Result> SP_ListarCasas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListarCasas_Result>("SP_ListarCasas");
        }
    
        public virtual ObjectResult<SP_ObtenerCasasFiltradas_Result> SP_ObtenerCasasFiltradas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerCasasFiltradas_Result>("SP_ObtenerCasasFiltradas");
        }
    
        public virtual ObjectResult<SP_ObtenerTodasCasas_Result> SP_ObtenerTodasCasas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerTodasCasas_Result>("SP_ObtenerTodasCasas");
        }
    }
}
